.TH "The AdvanceCOMP Authors" 1
.SH NAME
authors \(hy The AdvanceCOMP Authors
.SH AUTHORS 
.PD 0
.IP \(bu
Andrea Mazzoleni
.PD
.SH ACKNOWLEDGMENTS 
.PD 0
.IP \(bu
Filipe Estima
.PD
.SH LIBRARIES 
.RS 0
.PD 0
.HP 4
.I zlib
Copyright Jean\(hyloup Gailly and Mark Adler
.HP 4
.I 7z
Copyright Igor Pavlov
.HP 4
.I bzip2
Copyright Julian Seward
.HP 4
.I getopt
Copyright DJ Delorie
.PD
.RE
