.TH "AdvanceCOMP Authors" 1
.SH NAME
authors \(hy AdvanceCOMP Authors
.SH AUTHORS 
The author of AdvanceCOMP and releated utilities is
Andrea Mazzoleni.
.PP
You can contact me sending an email at:
.PP
.RS 4
amadvance@users.sourceforge.net
.RE
.SH ACKNOWLEDGMENTS 
A lot of other people helped submitting patches, bug reports
and generic comments. A special mention to:
.PD 0
.IP \(bu
Filipe Estima
.PD
