.TH "AdvanceCOMP Installation" 1
.SH NAME
advcomp \(hy AdvanceCOMP Installation
.PP
As root or user type:
.PP
.RS 4
./configure
.PD 0
.PP
.PD
make
.PD 0
.PP
.PD
.RE
.PP
To check the generated executable type:
.PP
.RS 4
make check
.PD 0
.PP
.PD
.RE
.PP
and as root to install the programs and the documentation
type:
.PP
.RS 4
make install
.PD 0
.PP
.PD
.RE
.PP
The documentation is in the man pages:
.PP
.RS 4
man advdef
.PD 0
.PP
.PD
man advzip
.PD 0
.PP
.PD
man advpng
.PD 0
.PP
.PD
man advmng
.PD 0
.PP
.PD
.RE
