.TH "AdvanceCOMP Compression Utilities" 1
.SH NAME
advcomp \(hy AdvanceCOMP Compression Utilities
.PP
AdvanceCOMP contains recompression utilities for your .zip archives,
.png images, .mng video clips and .gz files.
.PP
It runs in Linux, Mac OS X, DOS, Windows and in all the other
Unix like platforms.
.PP
The official site of AdvanceCOMP is:
.PP
.RS 4
http://advancemame.sourceforge.net
.RE
.PP
This package contains:
.RS 4
.PD 0
.HP 4
.I advzip
Recompression and test utility for zip files
.HP 4
.I advpng
Recompression utility for png files
.HP 4
.I advmng
Recompression utility for mng files
.HP 4
.I advdef
Recompression utility for deflate streams in .png, .mng and .gz files
.PD
.RE
